### ISSUE TITLE
Unsupported content type:multipart/mixed

### ISSUE THREAD

**Issue by mzTeamMeatMan** [cojs/busboy#44]
```
LINECONTENT:nodejs.Error: Unsupported content type: multipart/mixed; boundary=409ed440-5bfe-4c7e-b317-1a0735da6e8a
    at Busboy.parseHeaders (/data/lifekh-mp-nodejs-mobile-app-composition-sit/ROOT/node_modules/busboy/lib/main.js:75:9)
    at new Busboy (/data/lifekh-mp-nodejs-mobile-app-composition-sit/ROOT/node_modules/busboy/lib/main.js:22:10)
    at module.exports (/data/lifekh-mp-nodejs-mobile-app-composition-sit/ROOT/node_modules/co-busboy/index.js:31:16)
```

**Comment by AiPacinoDebug** [comment]
[formidable](https://github.com/node-formidable/formidable)
![1621423240775](https://user-images.githubusercontent.com/13598515/118804510-5e081700-b8d7-11eb-9d35-df5cd078475a.jpg)
